### ISSUE TITLE
Maintenance: Replace Moq library

### ISSUE THREAD

**Issue by sliedig** [aws-samples/aws-serverless-developer-experience-workshop-dotnet#19]
### Summary

Moq included [SponsorLink](https://github.com/devlooped/SponsorLink) from [version 4.20](https://github.com/moq/moq/releases/tag/v4.20.0). A https://github.com/moq/moq/issues/1372 has been raised.

from a privacy standpoint we should consider to moving away from Moq to another library such as [NSubstitute](https://nsubstitute.github.io/).

### Why is this needed?

Avoid sending data to 3rd parties.

### Solution

Replace [Moq](https://www.nuget.org/packages/Moq) dependencies with [NSubstitute](https://www.nuget.org/packages/NSubstitute) NuGet packages and refactor all unit tests to use new library instead.

**Comment by Creastoff** [comment]
I see you have already made the modifications for this, however here is an FYI for your other projects:

https://gist.github.com/Creastoff/280a33caa684db756c7cce91d318b41f
